llm:
  agent_model:
    name: "gpt-4"
    provider: "openai"
  reviser_model:
    name: "gpt-4o"
    provider: "openai"
  evaluator_model:
    name: "gpt-4o-mini"
    provider: "openai"

reviser:
  max_iterations: 3
  target_score: 94

logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'

evaluation:
  aspects:
    - relevance
    - coherence
    - accuracy
    - simplicity
  score_range:
    min: 0
    max: 100

openai:
  temperature: 0.7
  max_tokens: 1500

DEBUG: true